import type { ReactNode } from 'react';
import type { ViewStyle, TextStyle } from 'react-native';
import type { YearMonth, YearMonthPickerProps } from './YearMonthPicker';
export type YearMonthPickerSelectProps = {
    value?: YearMonth;
    onChange: (value: YearMonth) => void;
    placeholder?: string;
    label?: string;
    helperText?: string;
    errorMessage?: string;
    disabled?: boolean;
    required?: boolean;
    startYear?: number;
    endYear?: number;
    yearUnit?: string;
    monthUnit?: string;
    icon?: ReactNode;
    iconRight?: ReactNode;
    iconPosition?: 'left' | 'right' | 'top' | 'bottom';
    testID?: string;
    style?: ViewStyle;
    inputStyle?: TextStyle;
    labelStyle?: TextStyle;
    errorStyle?: TextStyle;
    containerStyle?: ViewStyle;
    pickerProps?: Partial<YearMonthPickerProps>;
};
declare const YearMonthPickerSelect: ({ value, onChange, placeholder, label, helperText, errorMessage, disabled, required, startYear, endYear, yearUnit, monthUnit, icon, iconRight, iconPosition, testID, style, inputStyle, labelStyle, errorStyle, containerStyle, pickerProps, }: YearMonthPickerSelectProps) => any;
export default YearMonthPickerSelect;
